builds:
- id: "clusterctl-aws"
  main: ./cmd/clusterawsadm
  binary: bin/clusterctl-aws
  env:
    - CGO_ENABLED=0
  ldflags:
  - -s -w 
  - -X 'sigs.k8s.io/cluster-api-provider-aws/v2/version.gitMajor={{.Major}}'
  - -X 'sigs.k8s.io/cluster-api-provider-aws/v2/version.gitMinor={{.Minor}}'
  - -X 'sigs.k8s.io/cluster-api-provider-aws/v2/version.gitVersion={{.Version}}'
  - -X 'sigs.k8s.io/cluster-api-provider-aws/v2/version.gitCommit={{.Commit}}'
  - -X 'sigs.k8s.io/cluster-api-provider-aws/v2/version.gitTreeState={{ if .IsGitDirty }}dirty{{ else }}clean{{ end }}'
  - -X 'sigs.k8s.io/cluster-api-provider-aws/v2/version.buildDate={{.Date}}'
  goos:
  - linux
  - darwin
  - windows 
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64

archives:
- id: clusterctl-aws
  builds:
  - clusterctl-aws
  format_overrides:
  - goos: windows
    format: zip
  name_template: "clusterctl_aws_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
